### ISSUE TITLE
Chemins d'image

### ISSUE THREAD

**Issue by PonteIneptique** [Lucaterre/Exercices-Framework-CSS#1]
Avant d'aller plus loin dans la correction, serait-il possible d'utiliser des chemins relatifs pour les images et fonds, afin qu'elles puissent s'afficher chez moi ?

Exemple dans Exercice2.html :

```html
<p><img src="/projets-web/enc-cours/images/fond2.jpg" alt="motifs géométriques variés de couleurs psychédéliques" class="rounded-circle" /></p>
```
en

```html
<p><img src="./img/fond2.jpg" alt="motifs géométriques variés de couleurs psychédéliques" class="rounded-circle" /></p>
```

Sans oublier de fournir l'image !

**Comment by Lucaterre** [comment]
Oups ! j'ai corrigé les chemins relatifs pour les images ainsi que pour les icônes et ajouté l'image manquante (img) !
